
const products = [
    {
      id: 1,
      title: "Smartphone",
      description: "Latest model with advanced features.",
      price: 14999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 4,
    },
    {
      id: 2,
      title: "Laptop",
      description: "Powerful laptop for work and gaming.",
      price: 49999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 3,
    },
    {
      id: 3,
      title: "Wireless Headphones",
      description: "Noise-canceling wireless headphones.",
      price: 2999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 4,
    },
    {
      id: 4,
      title: "Smart Watch",
      description: "Track fitness and stay connected.",
      price: 3999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 4,
    },
    {
      id: 5,
      title: "Bluetooth Speaker",
      description: "Portable speaker with high bass.",
      price: 1999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 5,
    },
    {
      id: 6,
      title: "DSLR Camera",
      description: "Capture stunning images with clarity.",
      price: 69999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 5,
    },
    {
      id: 7,
      title: "Gaming Mouse",
      description: "High precision gaming mouse.",
      price: 1299,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 4,
    },
    {
      id: 8,
      title: "Mechanical Keyboard",
      description: "RGB backlit mechanical keyboard.",
      price: 3499,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 5,
    },
    {
      id: 9,
      title: "External Hard Drive",
      description: "1TB storage for backups.",
      price: 4999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 4,
    },
    {
      id: 10,
      title: "Smart TV",
      description: "4K UHD smart TV with HDR.",
      price: 29999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 5,
    },
    {
      id: 11,
      title: "Tablet",
      description: "10-inch tablet for entertainment.",
      price: 9999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 4,
    },
    {
      id: 12,
      title: "Wireless Earbuds",
      description: "Comfortable and high-quality sound.",
      price: 2499,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 5,
    },
    {
      id: 13,
      title: "Power Bank",
      description: "10000mAh fast charging power bank.",
      price: 1999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 4,
    },
    {
      id: 14,
      title: "VR Headset",
      description: "Virtual reality experience.",
      price: 5999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 5,
    },
    {
      id: 15,
      title: "Smart Home Hub",
      description: "Control your smart devices easily.",
      price: 8999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 4,
    },
    {
      id: 16,
      title: "Fitness Tracker",
      description: "Track your health & fitness.",
      price: 2999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 4,
    },
    {
      id: 17,
      title: "Electric Toothbrush",
      description: "Advanced cleaning technology.",
      price: 1999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 5,
    },
    {
      id: 18,
      title: "Portable Projector",
      description: "HD portable movie projector.",
      price: 12999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 4,
    },
    {
      id: 19,
      title: "Car Vacuum Cleaner",
      description: "Compact and powerful car cleaner.",
      price: 2999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 4,
    },
    {
      id: 20,
      title: "Coffee Maker",
      description: "Brew fresh coffee instantly.",
      price: 3999,
      image: "https://picsum.photos/seed/picsum/200/300",
      rating: 5,
    },
  ];
  
  export default products;
  

